### ISSUE TITLE
(Temporarily?) use OAuth2 proxy for Kashti auth

### ISSUE THREAD

**Issue by technosophos** [brigadecore/kashti#148]
I know we'd like to have OAuth2 support for Kashti. In the near term, might we be able to use this service to accomplish that quickly? https://github.com/bitly/oauth2_proxy

I think we'd have to set it up to proxy both the Kashti dashboard and the upstream REST API. But if we documented proper setup, this would definitely make Kashti easier to use.

**Comment by jmo808** [comment]
I'm trying this out now, unfortunately my kube-lego went crazy and couldn't create the secret for the certificate and I got rate limited :/ But I'll report back when I can try this again.

**Comment by ese** [comment]
We are using https://github.com/kubernetes/ingress-nginx/ and https://github.com/bitly/oauth2_proxy to have oauth in kashti and brigade-api

These are the yamls FYI:

Ingress for kashti and brigade API
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: kashti-ingress
spec:
  rules:
  - host: kashti.domain
    http:
      paths:
      - backend:
          serviceName: kashti
          servicePort: 80
        path: /
      - backend:
          serviceName: brigade-api
          servicePort: 7744
        path: /brigade
  tls:
  - hosts:
    - kashti.domain
    secretName: kashti-cert
```

Ingress for oauth proxy
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kashti.domain
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2
  tls:
  - hosts:
    - kashti.domain
    secretName: kashti-cert
```

Kashti configmap
```yaml
apiVersion: v1
data:
  settings.js: |-
    var brigadeApiURL = 'https://kashti.domain/brigade';
    // End
kind: ConfigMap
metadata:
  name: kashti-conf
```
